consumer_services/urls.py
# consumer_services/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.login,name='login'),
    path('submit_request/', views.submit_request, name='submit_request'),
    path('representative_dashboard/', views.representative_dashboard, name='representative_dashboard'),
    path('track_request/', views.track_request, name='track_request'),
    path('register_user/', views.register_user, name='register_user'),
    path('register_representative/', views.register_representative, name='register_representative'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('editProfile/', views.editProfile, name='editProfile'),
]

gas_utility_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consumer_services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consumer_services/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class ServiceRequest(models.Model):
    class ServiceRequestStatus(models.TextChoices):
        IN_PROGRESS = 'In Progress', _('in_progress')
        RESOLVED = 'Resolved', _('resolved')

    class ServiceRequestType(models.TextChoices):
        GAS_CYLINDER_DELIVERY = 'Gas Cylinder Delivery', _('Gas Cylinder Delivery')
        GAS_LEAKAGE_COMPLAINT = 'Gas Leakage Complaint', _('Gas Leakage Complaint')
        CHANGE_OF_CONTACT_DETAILS = 'Change of Contact Details', _('Change of Contact Details')
        PAYMENT_RELETED_ISSUE = 'Payment Related Issues', _('Payment Related Issues')

    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    request_id = models.CharField(max_length=50, default=uuid.uuid4())
    request_title = models.CharField(max_length=100)
    request_status = models.CharField(
        max_length=50,
        choices=ServiceRequestStatus.choices,
        default=ServiceRequestStatus.IN_PROGRESS,
    )
    service_request_type = models.CharField(
        max_length=50,
        choices=ServiceRequestType.choices,
        default=ServiceRequestType.GAS_CYLINDER_DELIVERY,
    )
    details = models.TextField()
    attachment = models.FileField(upload_to='attachments/', null=True, blank=True)
    submission_date = models.DateTimeField(null=True, blank=True)
    resolution_date = models.DateTimeField(null=True, blank=True)
    

class UserProfile(models.Model):
    class UserType(models.TextChoices):
        USER = 'us', _('user')
        REPRESENTATIVE = 'rp', _('representative')

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(
        max_length=2,
        choices=UserType.choices,
        default=UserType.USER,
    )

    # Add additional customer profile fields here

consumer_services/forms.py
from django import forms
from .models import ServiceRequest, UserProfile
from django.contrib.auth.models import User

class ServiceRequestForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['request_title', 'service_request_type', 'details', 'attachment']

class RequestTrackingForm(forms.Form):
    request_id = forms.CharField(max_length=100)

class RequestStatusUpdateForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['request_id', 'request_status']
        widgets = {'request_id': forms.HiddenInput()}


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

consumer_services/views.py
# consumer_services/views.py
from datetime import datetime
import uuid
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import UserProfile, ServiceRequest
from .forms import RequestStatusUpdateForm, ServiceRequestForm, RequestTrackingForm, UserForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages



def register_user(request):
    return create_user(request=request, user_type=UserProfile.UserType.USER)


def register_representative(request):
    return create_user(request=request, user_type=UserProfile.UserType.REPRESENTATIVE)


def create_user(request, user_type: UserProfile.UserType):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            profile = UserProfile()
            user = form.save()
            profile.user = user
            profile.user_type = user_type
            profile.save()
            # auth_login(request, user)
            form = UserCreationForm()
            return redirect('login')
    elif request.user and request.user.username:
        return redirect('submit_request')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())

            userProfile = UserProfile.objects.get(user = form.get_user())

            if userProfile.user_type == userProfile.UserType.USER.value:
                return redirect('track_request')
            else:
                return redirect('representative_dashboard') # return representative dashboard html
    elif request.user and request.user.username:
        userProfile = UserProfile.objects.get(user = request.user)

        if userProfile.user_type == UserProfile.UserType.USER.value:
            return redirect('track_request')
        else:
            return redirect('representative_dashboard') # return representative dashboard html
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('login')


@login_required(login_url='login')
def editProfile(request):
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()

        forget_password_form = PasswordChangeForm(request.user, request.POST)
        if forget_password_form.is_valid():
            updated_user = forget_password_form.save()
            update_session_auth_hash(request, updated_user)

        return redirect('logout')
    else:
        user_form = UserForm(instance=request.user)
        forget_password_form = PasswordChangeForm(request.user)

    return render(request, 'edit_profile.html', {'user_form' : user_form, 'forget_password_form': forget_password_form})


@login_required
def submit_request(request):
    request_id = ''
    if request.method == 'POST':
        form = ServiceRequestForm(request.POST, request.FILES)
        if form.is_valid():
            request_obj = form.save(commit=False)
            request_obj.customer = request.user
            request_obj.request_id = uuid.uuid4()
            request_obj.submission_date = datetime.now()
            request_obj.save()
            request_id = request_obj.request_id
            form = ServiceRequestForm()
            return render(request, 'submit_request.html', {'form': form, 'request_id' : request_id})
    else:
        form = ServiceRequestForm()
    return render(request, 'submit_request.html', {'form': form})

@login_required
def track_request(request):
    serviceRequests = ServiceRequest.objects.filter(customer=request.user.id)
    if request.method == 'POST':
        form = RequestTrackingForm(request.POST)
        if form.is_valid():
            request_id = form.cleaned_data['request_id']
            service_request = ServiceRequest.objects.get(request_id=request_id)
            return render(request, 'track_request.html', {'service_request': service_request, 'service_requests': serviceRequests})
    else:
        form = RequestTrackingForm()
    return render(request, 'track_request.html', {'form': form, 'service_requests': serviceRequests})


@login_required
def representative_dashboard(request):
    choices = ServiceRequest.ServiceRequestStatus.choices
    if request.method == 'POST':
        print('body', request.body)
        print(request.POST['request_status'])
        request_status = request.POST['request_status']
        request_id = request.POST['request_id']
        service_request = ServiceRequest.objects.get(request_id=request_id)
        service_request.request_status = request_status
        service_request.resolution_date = datetime.now()
        service_request.save()
        serviceRequests = ServiceRequest.objects.all()
        for a in serviceRequests:
            print(a.request_status)
        return render(request, 'representative_dashboard.html', {'choices':choices, 'service_requests': serviceRequests})
    else:
        pass
    
    serviceRequests = ServiceRequest.objects.all()
    print(choices)
    return render(request, 'representative_dashboard.html', {'choices':choices, 'service_requests': serviceRequests})

consumer_services/templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/newstyle.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>

    <title>Track Service Requests</title>

</head>
<body class="container">
    <div style="position: relative;text-align:right;margin:5px 10px 0px 0px;">
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'logout' %}'">
            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
          </button>
    </div>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form.as_p}}
            <input class="btn btn-primary" type="submit" value="Update" name="" id="">
        </form>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{forget_password_form.as_p}}
            <input class="btn btn-primary" type="submit" value="Update" name="" id="">
        </form>
        {% comment %} <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'change_password' %}'">
            <i class="fa fa-sign-out" aria-hidden="true"></i> Change Password
        </button> {% endcomment %}
    </div>

</body>
</html>

consumer_services/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
    
    <title>Login</title>
</head>
<body>
    <div style="max-width: 400px; margin: 0 auto; padding: 20px; background-color: #f8f8f8; border-radius: 5px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% comment %} <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="username" class="form-control" id="username" placeholder="name@example.com" name="username">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" placeholder="name@example.com" name="password">
            </div> {% endcomment %}
            <div>
                <div class="row">
                    <div class="col-auto" >
                        <button type="submit" class="btn btn-primary mb-3">Login</button>
                    </div>
                    <div class="col-auto row">
                        <button type="button" class="btn btn-primary mb-3" onclick="location.href='{% url 'register_user' %}'">User Registration</button>
                        <button type="button" class="btn btn-primary mb-3" onclick="location.href='{% url 'register_representative' %}'">Representative Registration</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>
</html>

consumer_services/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <div style="max-width: 400px; margin: 0 auto; padding: 20px; background-color: #f8f8f8; border-radius: 5px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
        <h2>Register</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" style="background-color: #007BFF; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">Register</button>
        </form>
    </div>
</body>
</html>

consumer_services/templates/representative_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/newstyle.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>

    <title>Track Service Requests</title>

</head>

<body class="container">
    <div style="position: relative;text-align:right;margin:5px 10px 0px 0px;">
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'editProfile' %}'">
            <i class="fa fa-user" aria-hidden="true"></i> Edit Profile
        </button>
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'logout' %}'">
            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
        </button>
    </div>
    <div>
        <h2>
            All Requests:
        </h2>
        <table class="table table-bordered">
            <tr>
                <th>Request ID</th>
                <th>Title</th>
                <th>Status</th>
                <th>Submission Date</th>
                <th>Resolution Date</th>
                <th>Attachment</th>
                <th>Action</th>
            </tr>
            {% for service_request in service_requests %}
            <tr>
                <td>{{service_request.request_id}}</td>
                <td>{{service_request.request_title}}</td>
                <td>{{service_request.request_status}}</td>
                <td>{{service_request.submission_date}}</td>
                {% if service_request.request_status == "In Progress" %}
                    <td></td>
                {% elif service_request.request_status == "Resolved" %}
                    <td>{{service_request.resolution_date}}</td>
                
                {% endif %}

                {% comment %} {% if service_request.resolution_date %}
                <td>{{service_request.resolution_date}}</td>
                {% else %}
                <td></td>
                {% endif %}  {% endcomment %}

                {% if service_request.attachment %}
                <td><a href="{{ MEDIA_URL }}{{service_request.attachment}}" target="_blank" />View</td>
                {% else %}
                <td></td>
                {% endif %}

                <td><a class="btn btn-sm btn-primary" data-bs-toggle="modal"
                        href="#exampleModalToggle-{{service_request.request_id}}" role="button">Update Status</a></td>
                <div class="modal fade" id="exampleModalToggle-{{service_request.request_id}}" aria-hidden="true"
                    aria-labelledby="exampleModalToggleLabel" tabindex="-1">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalToggleLabel">{{service_request.request_title}}
                                </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <form method="post">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div style="word-break:break-word">
                                        <strong>Details: </strong> {{service_request.details}}
                                    </div>
                                    <div class="mt-3">

                                        {% comment %} {% csrf_token %}
                                        {{form.as_p}} {% endcomment %}
                                        <select aria-label="Request Status" class="form-select" name="request_status">
                                            {% for k, v in choices %}
                                            {% if k == service_request.request_status %}
                                            <option value="{{ k }}" selected>{{k}}</option>
                                            {% else %}
                                            <option value="{{ k }}">{{k}}</option>
                                            {% endif %}
                                            {% endfor %}
                                        </select>
                                        <input type="hidden" name="request_id" id="id_request_id"
                                            value="{{service_request.request_id}}">

                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary" data-bs-target="#exampleModalToggle2"
                                        data-bs-toggle="modal" data-bs-dismiss="modal">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </tr>
            {% endfor %}
        </table>
    </div>

</body>

</html>

consumer_services/templates/submit_request.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="icon" href="{% static 'css/img/logo.png' %}">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>

    <title>Submit Service Request</title>
</head>
<body class="container">
      <div style="position: relative;text-align:right;margin:5px 10px 0px 0px;">
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'editProfile' %}'">
          <i class="fa fa-user" aria-hidden="true"></i> Edit Profile
        </button>
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'logout' %}'">
            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
          </button>
    </div>
    <div>
      <h2 style="text-align:center">Submit Service Request</h2>
      <form method="post" enctype="multipart/form-data" class="request-form">
          {% if request_id  %}
              <div class="alert alert-success" role="alert">
                  Service request created successfully..!!<br>
                  Please note following request id to check the status.
                  Request ID:<br> <strong>{{ request_id | escape }}</strong>
              </div>
          
          {% endif %}
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Submit Request</button>
          <button type="button" class="btn btn-primary" ><a href="{% url 'track_request' %}"
              style="color: white; text-decoration:none">Track Request</a></button>
      </form>
    </div>
</body>
</html>

consumer_services/templates/track_request.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/newstyle.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>

    <title>Track Service Request</title>

</head>
<body class="container">

    <div style="position: relative;text-align:right;margin:5px 10px 0px 0px;">
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'editProfile' %}'">
            <i class="fa fa-user" aria-hidden="true"></i> Edit Profile
        </button>
        <button type="button" class="btn btn-dark btn-sm" onclick="location.href='{% url 'logout' %}'">
            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
          </button>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Track Request"/>
            <button type="button" class="btn btn-primary" onclick="location.href='{% url 'submit_request' %}'">Raise a request</a></button>
        </form>

        {% if service_request %}
            <h2>Request Details</h2>
            <p>Request Title: {{ service_request.request_title }}</p>
            <p>Detail: {{ service_request.details }}</p>
            <p>Status: {{ service_request.request_status }}</p>
            <p>Submission Date: {{ service_request.submission_date }}</p>
            <p>Resolution Date: {{ service_request.resolution_date }}</p>
        {% endif %}

        <h2>
            All Requests:
        </h2>
        <table class="table table-bordered">
            <tr>
                <th>Request ID</th>
                <th>Title</th>
                <th>Status</th>
                <th>Submission Date</th>
                <th>Resolution Date</th>
                <th>Attachment</th>
            </tr>
            {% for service_request in service_requests %}
                <tr>
                    <td>{{service_request.request_id}}</td>
                    <td>{{service_request.request_title}}</td>
                    <td>{{service_request.request_status}}</td>
                    <td>{{service_request.submission_date}}</td>
                    <td>{{service_request.resolution_date}}</td>

                    {% if service_request.attachment %}
                    <td><a href="{{ MEDIA_URL }}{{service_request.attachment}}" target="_blank"/>View</td>
                    {% else %}
                    <td></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>

</body>
</html>